### ISSUE TITLE
import::from doesn't seem to work from vignettes

### ISSUE THREAD

**Issue by krlmlr** [smbache/import#10]
unless package is already imported (e.g., via `requireNamespace`).

See my [test repo](https://github.com/krlmlr/import.vignette). It contains a vignette that uses `import::from`. Test: `R CMD build .`.

For package `knitr`, this works (tag [knitr-works](https://github.com/krlmlr/import.vignette/tree/knitr-works)). For package `tidyr`, this doesn't (tag tidyr-breaks), unless the package is loaded via `requireNamespace` before (tag with-requireNamespace).

Would anything break if `requireNamespace` is called in `import::from` et al.?

**Comment by smbache** [comment]
I am a little puzzled: `import::from` calls `loadNamespace`. Should that not be enough?

**Comment by smbache** [comment]
from the docs: `requireNamespace` is a wrapper for `loadNamespace` analogous to `require` that returns a logical value.

**Comment by krlmlr** [comment]
It seems to be a way to cure symptoms: https://github.com/krlmlr/import.vignette/commit/f307a558ac5aa54e7e8d22dac87b2917db4f47fa. Would it be too much trouble for you to test my reprex? :-)

**Comment by smbache** [comment]
No, but I cant @ the moment... busy at work ;)

**Comment by krlmlr** [comment]
Me too. I'm pretty sure the example in the introducing post shows what's wrong, but the cure I found might not be the right one. Thanks for looking into it.

**Comment by smbache** [comment]
Sure! Bugs need to be removed, right?!

**Comment by krlmlr** [comment]
I guess the default value `.library = .libPaths()[1L]` is responsible for the behavior we're seeing here. My cure works, because if a package is loaded it doesn't matter if it can be found in the `.library`. Why is it important to look only at the first entry of `.libPaths()`?

**Comment by smbache** [comment]
I've been tricked myself to believe a package was installed in a specific library; and when someone updated the package that was installed in the global library, my code broke. The problem was not easy to find. I believe it's safer to be very explicit about library paths.

**Comment by krlmlr** [comment]
I thought you'd rather care about the package version (#7). I'm using `.library = .libPaths()` in vignettes, seems to work.
