### ISSUE TITLE
Join tidyverse

### ISSUE THREAD

**Issue by hyiltiz** [smbache/import#24]
This packages aims to keep the namespace as clean as possible, making it possible to only import functions that will later be used by the user explicitly. This reduces name clashes in the namespace, and keeps the program namepsace tidy rather than messy. Would it be possible to apply to join tidyverse?

**Comment by torfason** [comment]
It certainly is tidy, if perhaps not in the exact same way as the "tidyverse" meaning of the word. More to the point, the maintainers of the tidyverse are the ones who decide which packages should be included in the tidyverse, so discussions of joining the tidyverse would be better addressed there.

[ suggest-closing ]
