### ISSUE TITLE
CI on windows seems like more trouble than it is worth, propose to remove it

### ISSUE THREAD

**Issue by torfason** [smbache/import#38]
Most recently it failed because of problems with installing `vctrs` on which `dplyr` depends(!). Both mac and linux are passing. Having a CI that keeps failing for non-material reasons slows the workflow and forces repeated workarounds that might end up breaking things that matter.

I'll update the latest pull request to remove it unless there are very strong objections.

The package will nevertheless be checked on Windows as part of release to CRAN.

**Comment by smbache** [comment]
Ok - we can do that for now.

Do we need dplyr?

**Comment by torfason** [comment]
It's used in examples so according to guidelines it should be listed in `Suggest`, causing CI to install it and fail. Failed CI because of a misconfigured server seems like a bad reason to remove it, the examples are quite relevant and compelling use cases.

**Comment by smbache** [comment]
Perhaps, but it is itself a big install as well, so also a bit of a cost. But removing windoze is fine with me for now.

**Comment by torfason** [comment]
Right, but including it in Suggests _only_ causes it to be installed by R-Check servers, not by end users, so there is no cost to end users.

**Comment by torfason** [comment]
Inded up removing dplyr instead, because removing windows-latest from the actions on the branch does not remove the requirement for it to pass on master, the branch would not merge. I guess that would not happen until after the branch is merged. So, this is closed as wontfix for now. If windows CI starts acting up again we can revisit this.
